# Generated by Django 4.2 on 2023-05-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_img',
            name='delay',
            field=models.IntegerField(null=True, verbose_name='Image delay'),
        ),
    ]
