# Generated by Django 4.2 on 2023-05-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_img_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_img',
            name='size',
            field=models.IntegerField(default=100, verbose_name='Image size'),
        ),
        migrations.AlterField(
            model_name='about_img',
            name='delay',
            field=models.FloatField(null=True, verbose_name='Image delay'),
        ),
    ]
