# Generated by Django 4.2 on 2023-05-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_img_size_alter_about_img_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_img',
            name='style',
            field=models.IntegerField(default=0, verbose_name='Image style'),
        ),
    ]
