# Generated by Django 4.2 on 2023-05-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about_img_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_img',
            name='delay',
        ),
        migrations.RemoveField(
            model_name='about_img',
            name='size',
        ),
        migrations.RemoveField(
            model_name='about_img',
            name='style',
        ),
    ]
