# Generated by Django 4.2 on 2023-05-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_about_img_delay_remove_about_img_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('title1', models.CharField(max_length=60, verbose_name='Title 1')),
                ('title2', models.CharField(max_length=60, verbose_name='Title 2')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('years', models.IntegerField(verbose_name='Experience years')),
                ('years_text', models.CharField(max_length=60, verbose_name='Years text')),
                ('experience', models.CharField(max_length=60, verbose_name='Experience text')),
                ('chef_count', models.IntegerField(verbose_name='Chef count')),
                ('chef_status', models.CharField(max_length=60, verbose_name='Chef status')),
                ('chef_text', models.CharField(max_length=60, verbose_name='Chef text')),
                ('btn_name', models.CharField(max_length=60, verbose_name='Button name')),
            ],
            options={
                'verbose_name': 'About_Us',
                'verbose_name_plural': 'About_Us',
            },
        ),
    ]
