# Generated by Django 4.2 on 2023-05-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=60, verbose_name='Class name')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('name', models.CharField(max_length=60, verbose_name='Member name')),
                ('img', models.ImageField(upload_to='images', verbose_name='Member image')),
                ('position', models.CharField(max_length=60, verbose_name='Member designation')),
                ('site_1', models.CharField(blank=True, max_length=20, verbose_name='Site 1 name')),
                ('site_1_link', models.URLField(blank=True, max_length=50, verbose_name='site_1_link')),
                ('site_2', models.CharField(blank=True, max_length=20, verbose_name='Site 2 name')),
                ('site_2_link', models.URLField(blank=True, max_length=50, verbose_name='site_2_link')),
                ('site_3', models.CharField(blank=True, max_length=20, verbose_name='Site 3 name')),
                ('site_3_link', models.URLField(blank=True, max_length=50, verbose_name='site_3_link')),
            ],
            options={
                'verbose_name': 'Team_Members',
                'verbose_name_plural': 'Team_Members',
            },
        ),
    ]
