# Generated by Django 4.2 on 2023-05-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_service_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('fa_name', models.CharField(max_length=50, verbose_name='Fa icon name')),
                ('text', models.TextField(verbose_name='Text 1')),
                ('delay', models.FloatField(default=0.1, verbose_name='Show Delay seconds')),
            ],
            options={
                'verbose_name': 'Our_services',
                'verbose_name_plural': 'Our_services',
            },
        ),
        migrations.AlterModelOptions(
            name='service_titles',
            options={'verbose_name': 'Service_Titles', 'verbose_name_plural': 'Service_Titles'},
        ),
    ]
