# Generated by Django 4.2 on 2023-05-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('home', models.CharField(max_length=60, verbose_name='Home')),
                ('pages', models.CharField(max_length=60, verbose_name='Pages')),
                ('about', models.CharField(max_length=60, verbose_name='About')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('subtitle_text', models.CharField(max_length=60, verbose_name='Subtitle text')),
            ],
            options={
                'verbose_name': 'About_Titles',
                'verbose_name_plural': 'About_Titles',
            },
        ),
    ]
