# Generated by Django 4.2 on 2023-05-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_about_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('home', models.CharField(max_length=60, verbose_name='Home')),
                ('pages', models.CharField(max_length=60, verbose_name='Pages')),
                ('booking', models.CharField(max_length=60, verbose_name='Booking')),
                ('video_link', models.URLField(verbose_name='Video link')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('subtitle_text', models.CharField(max_length=60, verbose_name='Subtitle text')),
                ('name', models.CharField(max_length=60, verbose_name='Your name')),
                ('email', models.CharField(max_length=60, verbose_name='Your email')),
                ('date', models.CharField(max_length=60, verbose_name='Date & Time')),
                ('people', models.CharField(max_length=60, verbose_name='No Of People')),
                ('request', models.CharField(max_length=60, verbose_name='Special Request')),
                ('btn', models.CharField(max_length=60, verbose_name='Button name')),
            ],
            options={
                'verbose_name': 'Booking_Titles',
                'verbose_name_plural': 'Booking_Titles',
            },
        ),
        migrations.RemoveField(
            model_name='team_members',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='team_members',
            name='title',
        ),
    ]
