# Generated by Django 4.2 on 2023-05-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_booking_titles_remove_team_members_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User name')),
                ('email', models.EmailField(max_length=254, verbose_name='User email')),
                ('profession', models.CharField(max_length=50, null=True, verbose_name='User profession')),
                ('message', models.TextField(verbose_name='User review')),
                ('img', models.ImageField(default='users/img_default.png', upload_to='users', verbose_name='User image')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Review',
            },
        ),
    ]
