# Generated by Django 4.2 on 2023-05-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam_Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('home', models.CharField(max_length=60, verbose_name='Home')),
                ('pages', models.CharField(max_length=60, verbose_name='Pages')),
                ('team', models.CharField(max_length=60, verbose_name='Team')),
            ],
            options={
                'verbose_name': 'OurTeam_Titles',
                'verbose_name_plural': 'OurTeam_Titles',
            },
        ),
    ]
