# Generated by Django 4.2 on 2023-05-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_ourteam_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('home', models.CharField(max_length=60, verbose_name='Home')),
                ('pages', models.CharField(max_length=60, verbose_name='Pages')),
                ('review', models.CharField(max_length=60, verbose_name='Review')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('subtitle_text', models.CharField(max_length=60, verbose_name='Subtitle text')),
            ],
            options={
                'verbose_name': 'Review_Titles',
                'verbose_name_plural': 'Review_Titles',
            },
        ),
    ]
