# Generated by Django 4.2 on 2023-05-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_review_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('name', models.CharField(max_length=60, verbose_name='Your name')),
                ('email', models.CharField(max_length=60, verbose_name='Your email')),
                ('profession', models.CharField(max_length=60, verbose_name='Your profession')),
                ('message', models.CharField(max_length=60, verbose_name='Your message')),
                ('btn', models.CharField(max_length=60, verbose_name='Button name')),
            ],
            options={
                'verbose_name': 'Review_Info',
                'verbose_name_plural': 'Review_Info',
            },
        ),
    ]
