# Generated by Django 4.2 on 2023-05-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_register_titles_alter_login_titles_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_titles',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='login_titles',
            old_name='username',
            new_name='username1',
        ),
        migrations.RenameField(
            model_name='register_titles',
            old_name='username',
            new_name='username1',
        ),
    ]
