# Generated by Django 4.2 on 2023-05-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_password_login_titles_password1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_titles',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
