# Generated by Django 4.2 on 2023-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_menu_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Menu Group name')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('num', models.IntegerField(verbose_name='Menu Group number')),
                ('fa_name', models.CharField(default='utensils', max_length=50, verbose_name='Fa icon name')),
            ],
            options={
                'verbose_name': 'Menu_Group',
                'verbose_name_plural': 'Menu_Group',
            },
        ),
    ]
