# Generated by Django 4.2 on 2023-05-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_menu_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Item name')),
                ('text', models.CharField(max_length=100, verbose_name='Item about')),
                ('price', models.IntegerField(verbose_name='Item price')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menugroup', to='main.menu_group')),
            ],
            options={
                'verbose_name': 'Menu_List',
                'verbose_name_plural': 'Menu_List',
            },
        ),
    ]
