# Generated by Django 4.2 on 2023-05-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_menu_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_list',
            name='img',
            field=models.ImageField(blank=True, upload_to='menu', verbose_name='Item image'),
        ),
    ]
