# Generated by Django 4.2 on 2023-05-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_menu_list_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=60, verbose_name='About name')),
                ('contact', models.CharField(max_length=60, verbose_name='Contact name')),
                ('reserv', models.CharField(max_length=60, verbose_name='Reservation name')),
                ('privacy', models.CharField(max_length=60, verbose_name='Privacy name')),
                ('terms', models.CharField(max_length=60, verbose_name='Terms name')),
            ],
            options={
                'verbose_name': 'Footer_Company',
                'verbose_name_plural': 'Footer_Company',
            },
        ),
    ]
