# Generated by Django 4.2 on 2023-05-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_footer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_company',
            name='title',
            field=models.CharField(default=2, max_length=60, verbose_name='Block title'),
            preserve_default=False,
        ),
    ]
