# Generated by Django 4.2 on 2023-05-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_footer_company_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Block title')),
                ('adress', models.URLField(verbose_name='Adress')),
                ('phone', models.CharField(max_length=60, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('social_name1', models.CharField(max_length=50, verbose_name='Social name 1')),
                ('social_link1', models.URLField(verbose_name='Link 1')),
                ('social_name2', models.CharField(max_length=50, verbose_name='Social name 2')),
                ('social_link2', models.URLField(verbose_name='Link 2')),
                ('social_name3', models.CharField(max_length=50, verbose_name='Social name 3')),
                ('social_link3', models.URLField(verbose_name='Link 3')),
                ('social_name4', models.CharField(max_length=50, verbose_name='Social name 4')),
                ('social_link4', models.URLField(verbose_name='Link 4')),
            ],
            options={
                'verbose_name': 'Contact_Adress',
                'verbose_name_plural': 'Contact_Adress',
            },
        ),
    ]
