# Generated by Django 4.2 on 2023-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_contact_adress_adress_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Block title')),
                ('work_day', models.CharField(max_length=60, verbose_name='Working days')),
                ('work_hours', models.CharField(max_length=60, verbose_name='Working hours')),
                ('delivery', models.CharField(max_length=60, verbose_name='Delivery')),
                ('delyvery_hours', models.CharField(max_length=60, verbose_name='Delivery hours')),
            ],
            options={
                'verbose_name': 'Footer_Opening',
                'verbose_name_plural': 'Footer_Opening',
            },
        ),
    ]
