# Generated by Django 4.2 on 2023-05-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_footer_opening'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer_opening',
            old_name='delyvery_hours',
            new_name='delivery_hours',
        ),
    ]
