# Generated by Django 4.2 on 2023-05-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_delyvery_hours_footer_opening_delivery_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Page title')),
                ('page_name', models.CharField(max_length=60, verbose_name='Page name')),
                ('block_name1', models.CharField(max_length=60, verbose_name='Block name home')),
                ('block_name2', models.CharField(max_length=60, verbose_name='Block name about')),
                ('block_name3', models.CharField(max_length=60, verbose_name='Block name service')),
                ('block_name4', models.CharField(max_length=60, verbose_name='Block name menu')),
                ('block_name5', models.CharField(max_length=60, verbose_name='Block name pages')),
                ('block_name6', models.CharField(max_length=60, verbose_name='Block name booking')),
                ('block_name7', models.CharField(max_length=60, verbose_name='Block name team')),
                ('block_name8', models.CharField(max_length=60, verbose_name='Block name review')),
                ('block_name9', models.CharField(max_length=60, verbose_name='Block name contact')),
                ('block_name10', models.CharField(max_length=60, verbose_name='Block name logout')),
                ('block_name11', models.CharField(max_length=60, verbose_name='Block name login')),
                ('block_name12', models.CharField(max_length=60, verbose_name='Block name signup')),
                ('block_name13', models.CharField(max_length=60, verbose_name='Block name book a table')),
            ],
            options={
                'verbose_name': 'Header_Titles',
                'verbose_name_plural': 'Header_Titles',
            },
        ),
    ]
