# Generated by Django 4.2 on 2023-05-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_header_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Title')),
                ('about', models.CharField(max_length=60, verbose_name='About')),
                ('btn', models.CharField(max_length=60, verbose_name='Booking button')),
                ('img', models.ImageField(upload_to='images', verbose_name='Home image')),
            ],
            options={
                'verbose_name': 'Home_Titles',
                'verbose_name_plural': 'Home_Titles',
            },
        ),
    ]
