# Generated by Django 4.2 on 2023-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_home_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_titles',
            name='about_en',
            field=models.CharField(max_length=256, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='home_titles',
            name='about_hy',
            field=models.CharField(max_length=256, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='home_titles',
            name='btn_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Booking button'),
        ),
        migrations.AddField(
            model_name='home_titles',
            name='btn_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Booking button'),
        ),
        migrations.AddField(
            model_name='home_titles',
            name='subtitle_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='home_titles',
            name='subtitle_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='home_titles',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='home_titles',
            name='title_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='home_titles',
            name='about',
            field=models.CharField(max_length=256, verbose_name='About'),
        ),
    ]
