# Generated by Django 4.2 on 2023-05-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_home_titles_about_en_home_titles_about_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_titles',
            name='block_name10_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name logout'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name10_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name logout'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name11_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name login'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name11_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name login'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name12_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name signup'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name12_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name signup'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name13_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name book a table'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name13_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name book a table'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name1_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name home'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name1_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name home'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name2_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name about'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name2_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name about'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name3_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name service'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name3_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name service'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name4_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name menu'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name4_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name menu'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name5_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name pages'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name5_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name pages'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name6_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name booking'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name6_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name booking'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name7_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name team'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name7_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name team'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name8_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name review'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name8_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name review'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name9_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name contact'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='block_name9_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block name contact'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='page_name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Page name'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='page_name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Page name'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Page title'),
        ),
        migrations.AddField(
            model_name='header_titles',
            name='title_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Page title'),
        ),
        migrations.AlterField(
            model_name='home_titles',
            name='subtitle',
            field=models.CharField(max_length=60, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='home_titles',
            name='subtitle_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='home_titles',
            name='subtitle_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle'),
        ),
    ]
