# Generated by Django 4.2 on 2023-05-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_about_titles_about_en_about_titles_about_hy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_titles',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='about_titles',
            name='title_hy',
        ),
    ]
