# Generated by Django 4.2 on 2023-05-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_contact_info_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='btn_name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Button name'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='btn_name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Button name'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='chef_status_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Chef status'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='chef_status_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Chef status'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='chef_text_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Chef text'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='chef_text_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Chef text'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='experience_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Experience text'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='experience_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Experience text'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='text1_en',
            field=models.TextField(null=True, verbose_name='Text 1'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='text1_hy',
            field=models.TextField(null=True, verbose_name='Text 1'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='text2_en',
            field=models.TextField(null=True, verbose_name='Text 2'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='text2_hy',
            field=models.TextField(null=True, verbose_name='Text 2'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='title1_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title 1'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='title1_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title 1'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='title2_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title 2'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='title2_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title 2'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='years_text_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Years text'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='years_text_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Years text'),
        ),
    ]
