# Generated by Django 4.2 on 2023-05-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_about_us_btn_name_en_about_us_btn_name_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_members',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Member name'),
        ),
        migrations.AddField(
            model_name='team_members',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Member name'),
        ),
        migrations.AddField(
            model_name='team_members',
            name='position_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Member designation'),
        ),
        migrations.AddField(
            model_name='team_members',
            name='position_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Member designation'),
        ),
    ]
