# Generated by Django 4.2 on 2023-05-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_team_members_name_en_team_members_name_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_titles',
            name='home_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='service_titles',
            name='home_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='service_titles',
            name='pages_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='service_titles',
            name='pages_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='service_titles',
            name='service_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='service_titles',
            name='service_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='service_titles',
            name='subtitle_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='service_titles',
            name='subtitle_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='service_titles',
            name='subtitle_text_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle text'),
        ),
        migrations.AddField(
            model_name='service_titles',
            name='subtitle_text_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle text'),
        ),
        migrations.AddField(
            model_name='service_titles',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='service_titles',
            name='title_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
    ]
