# Generated by Django 4.2 on 2023-05-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_service_titles_home_en_service_titles_home_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_services',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text 1'),
        ),
        migrations.AddField(
            model_name='our_services',
            name='text_hy',
            field=models.TextField(null=True, verbose_name='Text 1'),
        ),
        migrations.AddField(
            model_name='our_services',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='our_services',
            name='title_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
    ]
