# Generated by Django 4.2 on 2023-05-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_contactus_email_en_contactus_email_hy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='email_hy',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='message_hy',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='name_hy',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='subject_en',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='subject_hy',
        ),
        migrations.AddField(
            model_name='contact_titles',
            name='contact_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='contact_titles',
            name='contact_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='contact_titles',
            name='home_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='contact_titles',
            name='home_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='contact_titles',
            name='pages_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='contact_titles',
            name='pages_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='contact_titles',
            name='subtitle_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='contact_titles',
            name='subtitle_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='contact_titles',
            name='subtitle_text_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle text'),
        ),
        migrations.AddField(
            model_name='contact_titles',
            name='subtitle_text_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle text'),
        ),
        migrations.AddField(
            model_name='contact_titles',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='contact_titles',
            name='title_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
    ]
