# Generated by Django 4.2 on 2023-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_contactus_email_en_remove_contactus_email_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='booking_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title booking'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='booking_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title booking'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='btn_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Button name'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='btn_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Button name'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='email_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Your email'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='email_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Your email'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='general_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title general'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='general_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title general'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='message_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Your message'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='message_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Your message'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Your name'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Your name'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='subject_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Your subject'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='subject_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Your subject'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='technical_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title technical'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='technical_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title technical'),
        ),
    ]
