# Generated by Django 4.2 on 2023-05-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_contact_info_booking_en_contact_info_booking_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_adress',
            name='adress_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='contact_adress',
            name='adress_hy',
            field=models.CharField(max_length=100, null=True, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='contact_adress',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block title'),
        ),
        migrations.AddField(
            model_name='contact_adress',
            name='title_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block title'),
        ),
    ]
