# Generated by Django 4.2 on 2023-05-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_contact_adress_adress_en_contact_adress_adress_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam_titles',
            name='home_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='ourteam_titles',
            name='home_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='ourteam_titles',
            name='pages_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='ourteam_titles',
            name='pages_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='ourteam_titles',
            name='team_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='ourteam_titles',
            name='team_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='ourteam_titles',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='ourteam_titles',
            name='title_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
    ]
