# Generated by Django 4.2 on 2023-05-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_review_titles_home_en_review_titles_home_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_info',
            name='btn_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Button name'),
        ),
        migrations.AddField(
            model_name='review_info',
            name='btn_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Button name'),
        ),
        migrations.AddField(
            model_name='review_info',
            name='email_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Your email'),
        ),
        migrations.AddField(
            model_name='review_info',
            name='email_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Your email'),
        ),
        migrations.AddField(
            model_name='review_info',
            name='message_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Your message'),
        ),
        migrations.AddField(
            model_name='review_info',
            name='message_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Your message'),
        ),
        migrations.AddField(
            model_name='review_info',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Your name'),
        ),
        migrations.AddField(
            model_name='review_info',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Your name'),
        ),
        migrations.AddField(
            model_name='review_info',
            name='profession_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Your profession'),
        ),
        migrations.AddField(
            model_name='review_info',
            name='profession_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Your profession'),
        ),
        migrations.AddField(
            model_name='review_info',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='review_info',
            name='title_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
    ]
