# Generated by Django 4.2 on 2023-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_review_info_btn_en_review_info_btn_hy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bg_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='bg_images', verbose_name='BG Image')),
                ('video_img', models.ImageField(upload_to='bg_images', verbose_name='Video Image')),
            ],
            options={
                'verbose_name': 'Bg_img',
                'verbose_name_plural': 'Bg_img',
            },
        ),
    ]
