# Generated by Django 4.2 on 2023-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_bg_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_titles',
            name='btn_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Button name'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='btn_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Button name'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='home_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='home_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='login_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='login_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='pages_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='pages_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='password1_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='password1_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='subtitle_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='subtitle_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='title_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='username1_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='login_titles',
            name='username1_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Username'),
        ),
    ]
