# Generated by Django 4.2 on 2023-05-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_register_titles_btn_en_register_titles_btn_hy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_titles',
            name='btn_en',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='btn_hy',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='email_hy',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='firstname_en',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='firstname_hy',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='home_en',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='home_hy',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='lastname_en',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='lastname_hy',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='pages_en',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='pages_hy',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='password1_en',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='password1_hy',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='password2_en',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='password2_hy',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='signup_en',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='signup_hy',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='subtitle_hy',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='title_hy',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='username1_en',
        ),
        migrations.RemoveField(
            model_name='register_titles',
            name='username1_hy',
        ),
        migrations.AddField(
            model_name='menu_titles',
            name='home_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='menu_titles',
            name='home_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='menu_titles',
            name='menu_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Menu'),
        ),
        migrations.AddField(
            model_name='menu_titles',
            name='menu_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Menu'),
        ),
        migrations.AddField(
            model_name='menu_titles',
            name='pages_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='menu_titles',
            name='pages_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='menu_titles',
            name='subtitle_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='menu_titles',
            name='subtitle_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='menu_titles',
            name='subtitle_text_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle text'),
        ),
        migrations.AddField(
            model_name='menu_titles',
            name='subtitle_text_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle text'),
        ),
        migrations.AddField(
            model_name='menu_titles',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='menu_titles',
            name='title_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
    ]
