# Generated by Django 4.2 on 2023-05-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_remove_register_titles_btn_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_group',
            name='subtitle_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='menu_group',
            name='subtitle_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='menu_group',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Menu Group name'),
        ),
        migrations.AddField(
            model_name='menu_group',
            name='title_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Menu Group name'),
        ),
    ]
