# Generated by Django 4.2 on 2023-05-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_menu_group_subtitle_en_menu_group_subtitle_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_list',
            name='text_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Item about'),
        ),
        migrations.AddField(
            model_name='menu_list',
            name='text_hy',
            field=models.CharField(max_length=100, null=True, verbose_name='Item about'),
        ),
        migrations.AddField(
            model_name='menu_list',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Item name'),
        ),
        migrations.AddField(
            model_name='menu_list',
            name='title_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='menu_list',
            name='price',
            field=models.CharField(max_length=60, verbose_name='Item price'),
        ),
    ]
