# Generated by Django 4.2 on 2023-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_footer_company_about_en_footer_company_about_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_opening',
            name='delivery_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Delivery'),
        ),
        migrations.AddField(
            model_name='footer_opening',
            name='delivery_hours_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Delivery hours'),
        ),
        migrations.AddField(
            model_name='footer_opening',
            name='delivery_hours_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Delivery hours'),
        ),
        migrations.AddField(
            model_name='footer_opening',
            name='delivery_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Delivery'),
        ),
        migrations.AddField(
            model_name='footer_opening',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Block title'),
        ),
        migrations.AddField(
            model_name='footer_opening',
            name='title_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Block title'),
        ),
        migrations.AddField(
            model_name='footer_opening',
            name='work_day_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Working days'),
        ),
        migrations.AddField(
            model_name='footer_opening',
            name='work_day_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Working days'),
        ),
        migrations.AddField(
            model_name='footer_opening',
            name='work_hours_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Working hours'),
        ),
        migrations.AddField(
            model_name='footer_opening',
            name='work_hours_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Working hours'),
        ),
    ]
