# Generated by Django 4.2 on 2023-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_register_titles_btn_en_register_titles_btn_hy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='people_count',
            field=models.PositiveIntegerField(max_length=50, verbose_name='People count'),
        ),
    ]
