# Generated by Django 4.2 on 2023-05-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_booking_people_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='people_count',
            field=models.PositiveIntegerField(verbose_name='People count'),
        ),
    ]
